/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Rectangle;

/**
 *
 * @author federico
 */
public class Window extends javax.swing.JFrame {
    int n; //variable encargada de guardar el numero de ecuaciones
    DefaultTableModel modelo = new DefaultTableModel(); //modelo de la tabla para ingresar las ecuaciones
    Boolean ban = false;
    
    public int getN(){ //Metodos para inicializar a n, y obtener su valor
        return n;
    }
    public void setN(int n){
        this.n = n;
    }
    
    
    /**
     * Creates new form LUPSOLVE
     */
    public Window() {
    	setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroDeEc = new javax.swing.JTextField();
        jButtonGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonLimpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUP - SOLVE");
        setBounds(new Rectangle(0, 0, 820, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "LUP - Solve"));
        jPanel1.setLayout(null);

        jLabel1.setText("N\u00FAmero de Ecuaciones:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 24, 140, 30);
        jPanel1.add(jTextFieldNumeroDeEc);
        jTextFieldNumeroDeEc.setBounds(160, 20, 110, 30);

        jButtonGenerar.setText("Generar ecuaciones");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerar);
        jButtonGenerar.setBounds(308, 20, 140, 34);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "x"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 549, 330);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(623, 60, 358, 330);

        jButtonLimpiar.setText("Limpiar");
        jPanel1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(763, 401, 80, 23);

        jButton2.setText("Resolver sistema");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 393, 130, 30);

        jLabel2.setText("Pasos:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(763, 29, 60, 20);
        
        btnAyudaMaual = new JButton("Ayuda - Manual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        				.addComponent(btnAyudaMaual, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(btnAyudaMaual)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        // TODO add your handling code here:
        try {
            this.setN(Integer.parseInt(jTextFieldNumeroDeEc.getText())); // convierte el texto del campo de valor de n en entero
            n = this.getN(); //obtiene el valor de n
            
            if(n<=1){ //validacion
               throw new Exception("Numero incorrecto!! Verifique"); //Validar que el numero de ecuaciones sea mayor que 2
            }
            Object columnas[] = new Object[n+1]; //Generar Numero de ecuaciones NxN en la tabla
            for (int i = 0; i < n+1; i++) { //for para ir añadiendo las columnas en la tabla
                if (i<n) {
                    columnas[i] = "x" + (i+1); //va añadiendo las incognitas en la tabla x1,x2,x3...xn
                } else{
                    columnas[i] = "B"; // agrega la ultima columna b 
                }
            }
            modelo = new DefaultTableModel(columnas , n); //modificar el tamaño de la tabla
            jTable.setModel(modelo); //dimension de la matriz
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage()); //Error cuando ingresan una letra en ves de un numero
        }
        
    
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldNumeroDeEc;
    private JButton btnAyudaMaual;
    // End of variables declaration//GEN-END:variables
}

